### ISSUE TITLE
Accept Extension

### ISSUE THREAD

**Issue by Alejandro-Suarez-Rincon** [OwlByTech/docu-stream#1]
Solo está soportando la extensión `.docx` y cuando se usa `.doc` el docu-stream server falla.

Tener en cuenta otras extensiones de Word como:
`.doc`
`.odt`
`.docx (Documento de Word 2010-365 y Word 2007)`
`.dotx (Plantilla de Word 2010-365 y Plantilla de Word 2007)`
`.dot`

**Comment by Camilo-Camargo** [comment]
Este pull request se cerrará debido a la falta de integración con soluciones open source para uso comercial que preserven la información adecuadamente. Por lo tanto, se recomienda utilizar esta biblioteca únicamente para formatos DOCX. Si encuentras archivos en formato DOC, se sugiere realizar la conversión utilizando las herramientas de Office.
